import type { Request, Response } from "express";
import { z } from "zod";
import { createId, getCatalog, saveCatalog } from "../models/catalog.model.js";
import type { Pack } from "../types.js";
const text = z.object({ en: z.string().min(1), ja: z.string().min(1) });
const optionalText = z.object({ en: z.string().default(""), ja: z.string().default("") });
const packInput = z.object({ slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), title: text, description: text, contents: text, galleryUrls: z.array(z.string().url()).default([]), characterIds: z.array(z.string()).default([]), tagIds: z.array(z.string()).default([]), collectionIds: z.array(z.string()).default([]), price: z.number().nonnegative(), compareAtPrice: z.number().nonnegative().optional(), isPublished: z.boolean().default(false), isFeatured: z.boolean().default(false), isBestseller: z.boolean().default(false), fileCount: z.number().int().nonnegative(), format: z.string().min(1), salesCount: z.number().int().nonnegative().default(0), patreonUrl: z.string().url(), createdAt: z.string().date() });
const refsValid = (catalog: Awaited<ReturnType<typeof getCatalog>>, pack: z.infer<typeof packInput>) => { const all = (ids: string[], values: { id: string }[]) => ids.every((id) => values.some((v) => v.id === id)); return all(pack.characterIds, catalog.characters) && all(pack.tagIds, catalog.tags) && all(pack.collectionIds, catalog.collections); };
export const listPacks = async (_req: Request, res: Response) => res.json((await getCatalog()).packs);
export async function createPack(req: Request, res: Response) { const data = packInput.safeParse(req.body); if (!data.success) return res.status(422).json({ error: data.error.flatten() }); const catalog = await getCatalog(); if (catalog.packs.some((p) => p.slug === data.data.slug)) return res.status(409).json({ error: "Slug already exists" }); if (!refsValid(catalog, data.data)) return res.status(422).json({ error: "Invalid catalog reference" }); const pack: Pack = { id: createId("pk"), ...data.data }; catalog.packs.unshift(pack); await saveCatalog(catalog); return res.status(201).json(pack); }
export async function updatePack(req: Request, res: Response) { const data = packInput.partial().safeParse(req.body); if (!data.success) return res.status(422).json({ error: data.error.flatten() }); const catalog = await getCatalog(); const index = catalog.packs.findIndex((p) => p.id === req.params.id); if (index < 0) return res.status(404).json({ error: "Pack not found" }); const pack = { ...catalog.packs[index], ...data.data }; if (!refsValid(catalog, pack)) return res.status(422).json({ error: "Invalid catalog reference" }); catalog.packs[index] = pack; await saveCatalog(catalog); return res.json(pack); }
export async function deletePack(req: Request, res: Response) { const catalog = await getCatalog(); const before = catalog.packs.length; catalog.packs = catalog.packs.filter((p) => p.id !== req.params.id); if (before === catalog.packs.length) return res.status(404).json({ error: "Pack not found" }); await saveCatalog(catalog); return res.status(204).end(); }
export async function createCharacter(req: Request, res: Response) { const data = z.object({ slug: z.string(), animeId: z.string(), name: text, description: optionalText.default({ en: "", ja: "" }) }).safeParse(req.body); if (!data.success) return res.status(422).json({ error: data.error.flatten() }); const catalog = await getCatalog(); if (!catalog.animes.some((a) => a.id === data.data.animeId)) return res.status(422).json({ error: "Invalid animeId" }); const character = { id: createId("ch"), ...data.data }; catalog.characters.push(character); await saveCatalog(catalog); return res.status(201).json(character); }
export async function createTag(req: Request, res: Response) { const data = z.object({ slug: z.string(), label: text }).safeParse(req.body); if (!data.success) return res.status(422).json({ error: data.error.flatten() }); const catalog = await getCatalog(); const tag = { id: createId("tg"), ...data.data }; catalog.tags.push(tag); await saveCatalog(catalog); return res.status(201).json(tag); }
export async function createCollection(req: Request, res: Response) { const data = z.object({ slug: z.string(), title: text, description: optionalText.default({ en: "", ja: "" }) }).safeParse(req.body); if (!data.success) return res.status(422).json({ error: data.error.flatten() }); const catalog = await getCatalog(); const collection = { id: createId("co"), ...data.data }; catalog.collections.push(collection); await saveCatalog(catalog); return res.status(201).json(collection); }
